query GitActivity {
  GitActivity {
    id
    url
    name
    description
    updated
    stars
    issues
    forks
    language
    collaborators
    diskUsage
    pullRequests
    license
    branches {
      name
      committedDate
      commitUrl
      message
    }
  }
}
